name: Keep Render service alive

# triggers: schedule + manual
on:
  # every 5 minutes between 00:00 and 21:00 UTC
  schedule:
    - cron: '*/10 0-21 * * *'
  # so you can also trigger it by hand
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit health endpoint
        # fail the step if curl returns non-2xx
        run: |
          echo "Pinging health check..."
          curl --fail --retry 3 --retry-delay 5 \
            https://expense-tracker-khgs.onrender.com/api/v1/health \
            && echo "✅ Service is up" \
            || echo "⚠️ Service did not respond"
